### PR TITLE
Fix apcu function when apc ones are polyfilled with Zend Server's Data Cache

### LINKED ISSUE #94: Zend Server and APC functionality
Zend Server tries to implement compatibility with apc by registering compatibility functions with the same name as the APC functions.

http://files.zend.com/help/Zend-Server-6/content/zend_data_cache_-_configuration_directives.htm

Specifically, the option is "zend_datacache.apc_compatibility".  It looks like it gets aliased to zend_shm_cache_store, which mostly works.  Unfortunately, it doesn't support the array form of apc_store(), so every call results in errors:

"apc_store() expects parameter 1 to be string, array given"

It looks like this is a problem that other [projects](https://github.com/UnionOfRAD/lithium/issues/1119) have dealt with, and it looks like it's one that's been going on for 8 years or so, so I'm not expecting Zend to fix it anytime soon.

My inclination would be to add a check to see if the parameter to apcu_add() or apcu_store() is an array, and if so to call the apc function individually for each item in the array.  It would maintain compatibility with APC, and fix the issues with Zend Server.  It's a little bit of a hack, though, and I figured I'd ask before submitting a PR.

Alternatively, I could add support for Zend Data Cache to the Symfony Cache Component.

### PR DESCRIPTION
**Pull request by kategray**
Fixes #94 
Detect if Zend Server's Data Cache is enabled, and work around it's lack of support for the array syntax.

### CODE REVIEW

File: src/Apcu/bootstrap.php [hunk 1]
```diff
@@ -11,10 +11,14 @@
 
 if (!extension_loaded('apc') && !extension_loaded('apcu')) {
     return;
-}
-
-if (!function_exists('apcu_add')) {
+} else if (extension_loaded ('Zend Data Cache')) {
+    // Zend Data Cache refuses to load in the CLI, regardless of the configuration
+    if ('cli' != PHP_SAPI && false !== ini_get('zend_datacache.apc_compatibility')) {
+        require_once __DIR__ . DIRECTORY_SEPARATOR . 'bootstrap_zend.php';
```
Comment (keradus) [inline src/Apcu/bootstrap.php]: do we really need to load 2 files ?

File: src/Apcu/bootstrap.php [hunk 2]
```diff
@@ -11,10 +11,14 @@
 
 if (!extension_loaded('apc') && !extension_loaded('apcu')) {
     return;
-}
-
-if (!function_exists('apcu_add')) {
+} else if (extension_loaded ('Zend Data Cache')) {
+    // Zend Data Cache refuses to load in the CLI, regardless of the configuration
+    if ('cli' != PHP_SAPI && false !== ini_get('zend_datacache.apc_compatibility')) {
```
Comment (keradus) [inline src/Apcu/bootstrap.php]:
```
ker@dus:~$ cat x.php 
<?php echo PHP_SAPI;
ker@dus:~$ phpdbg -qrr x.php 
phpdbg
```

File: src/Apcu/bootstrap.php (hunk 1 above)
Comment (kategray) [inline src/Apcu/bootstrap.php]: I'm open to suggestions.  I was trying to keep the APCUIterator, as well as trying to avoid the overhead associated with the Zend path on non-zend servers.  I could have moved it to composer.json and loaded both files that way, or I could have combined the functionality into a single file, with different function definitions depending on which path was taken.

I also didn't want to force APC to have to run the compatibility code, either.

File: src/Apcu/bootstrap_zend.php [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+    function apcu_add($key, $var = null, $ttl = 0) {
+        if (is_array($key)) {
+            $errors = array ();
+            foreach ($key as $cache_key => $cache_value) {
+                if (!apc_add ($cache_key, $cache_value, $ttl)) {
+                    $errors[] = $cache_key;
+                }
+            }
+            return $errors;
+        } else {
```
Comment (keradus) [inline src/Apcu/bootstrap_zend.php]: no need for else after return

File: src/Apcu/bootstrap_zend.php [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+ * file that was distributed with this source code.
+ */
+
+/**
+ * Bootstrap for Zend Server Data Cache
+ */
+if (!function_exists('apc_add')) {
+    function apcu_add($key, $var = null, $ttl = 0) {
+        if (is_array($key)) {
+            $errors = array ();
```
Comment (keradus) [inline src/Apcu/bootstrap_zend.php]: weird spacing

File: src/Apcu/bootstrap_zend.php [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+        return apc_fetch($key, $success);
+    }
+
+    function apcu_cache_info($limited = false) { return apc_cache_info('user', $limited); }
+    function apcu_cas($key, $old, $new) { return apc_cas($key, $old, $new); }
+    function apcu_clear_cache() { return apc_clear_cache('user'); }
+    function apcu_dec($key, $step = 1, &$success = false) { return apc_dec($key, $step, $success); }
+    function apcu_delete($key) { return apc_delete($key); }
+
+
```
Comment (keradus) [inline src/Apcu/bootstrap_zend.php]: not needed

File: src/Apcu/bootstrap_zend.php [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+    function apcu_inc($key, $step = 1, &$success = false) { return apc_inc($key, $step, $success); }
+    function apcu_sma_info($limited = false) { return apc_sma_info($limited); }
+}
```
Comment (keradus) [inline src/Apcu/bootstrap_zend.php]: new line is missing

File: src/Apcu/bootstrap.php (hunk 2 above)
Comment (kategray) [inline src/Apcu/bootstrap.php]: I'm aware of that limitation.  Unfortunately, Zend Data Cache does the checking internally, and does not have the option that APC does to force enabling in the cli.

The point was to avoid adding the compatibility to the cli, since it wouldn't work anyway.  It will fail gracefully if that check fails - the apc functions will simply return false, the same as any other failure.

File: tests/Apcu/ApcuTest.php [hunk 7]
```diff
@@ -37,6 +37,30 @@ public function testApcu()
...
+            $this->assertEquals($value, apcu_fetch($key));
+        }
+
+        // Test add and array fetch.  As key is a duplicate, it should not be overwritten.  key3 should be created.
+        apcu_add($test2);
+        $correct = array ('key' => 'value1', 'key2' => 'value2', 'key3' => 'value4');
+        $this->assertEquals($correct, apcu_fetch(array_keys($correct)));
+    }
+
+
```
Comment (keradus) [inline tests/Apcu/ApcuTest.php]: double new line is wrong

File: tests/Apcu/ApcuTest.php [hunk 8]
```diff
@@ -37,6 +37,30 @@ public function testApcu()
         $this->assertArrayHasKey('cache_list', apcu_cache_info());
     }
 
+    public function testArrayCompatibility() {
+        // Test that arrays are properly written and read
```
Comment (keradus) [inline tests/Apcu/ApcuTest.php]: would be nice to test both, zend and non-zend logic

File: src/Apcu/bootstrap_zend.php (hunk 3 above)
Comment (kategray) [inline src/Apcu/bootstrap_zend.php]: You're right - it's not required.  I put it there for clarity, and included the brackets on the if statement (which are also not required) for clarity.

File: src/Apcu/bootstrap.php (hunk 2 above)
Comment (keradus) [inline src/Apcu/bootstrap.php]: why not add `phpdbg !== PHP_SAPI` ?

File: src/Apcu/bootstrap_zend.php (hunk 3 above)
Comment (keradus) [inline src/Apcu/bootstrap_zend.php]: brackets on if are standards
extra else is not needed, producing larger bytecode and so on

File: tests/Apcu/ApcuTest.php (hunk 8 above)
Comment (kategray) [inline tests/Apcu/ApcuTest.php]: It would. phpUnit makes it hard to override built in functions, and I was trying to do a minor contribution rather than an overhaul.  Ideally, I'd like it to be in an object that can be broken down better for unit testing, but that's more than just a minor fix.

There's also the issue of Zend refusing to run CLI, requiring a web-based unit test.

File: src/Apcu/bootstrap.php (hunk 2 above)
Comment (kategray) [inline src/Apcu/bootstrap.php]: Exclude that one, as well as cli?

File: src/Apcu/bootstrap_zend.php (hunk 5 above)
Comment (kategray) [inline src/Apcu/bootstrap_zend.php]: What's not needed?

File: src/Apcu/bootstrap.php [hunk 9]
```diff
@@ -11,20 +11,56 @@
...
-    function apcu_dec($key, $step = 1, &$success = false) { return apc_dec($key, $step, $success); }
-    function apcu_delete($key) { return apc_delete($key); }
-    function apcu_exists($keys) { return apc_exists($keys); }
-    function apcu_fetch($key, &$success = false) { return apc_fetch($key, $success); }
-    function apcu_inc($key, $step = 1, &$success = false) { return apc_inc($key, $step, $success); }
-    function apcu_sma_info($limited = false) { return apc_sma_info($limited); }
-    function apcu_store($key, $var = null, $ttl = 0) { return apc_store($key, $var, $ttl); }
+} elseif (extension_loaded('Zend Data Cache')) {
+    // Zend Data Cache refuses to load in the CLI, regardless of the configuration
+    if ('phpdbg' != PHP_SAPI && 'cli' != PHP_SAPI && false !== ini_get('zend_datacache.apc_compatibility')) {
```
Comment (stof) [inline src/Apcu/bootstrap.php]: please use struct comparison

File: src/Apcu/bootstrap.php [hunk 10]
```diff
@@ -11,20 +11,56 @@
...
-    function apcu_cas($key, $old, $new) { return apc_cas($key, $old, $new); }
-    function apcu_clear_cache() { return apc_clear_cache('user'); }
-    function apcu_dec($key, $step = 1, &$success = false) { return apc_dec($key, $step, $success); }
-    function apcu_delete($key) { return apc_delete($key); }
-    function apcu_exists($keys) { return apc_exists($keys); }
-    function apcu_fetch($key, &$success = false) { return apc_fetch($key, $success); }
-    function apcu_inc($key, $step = 1, &$success = false) { return apc_inc($key, $step, $success); }
-    function apcu_sma_info($limited = false) { return apc_sma_info($limited); }
-    function apcu_store($key, $var = null, $ttl = 0) { return apc_store($key, $var, $ttl); }
+} elseif (extension_loaded('Zend Data Cache')) {
```
Comment (stof) [inline src/Apcu/bootstrap.php]: `if` is enough as there is an early return

File: src/Apcu/bootstrap_zend.php (hunk 5 above)
Comment (keradus) [inline src/Apcu/bootstrap_zend.php]: there were too much empty lines

File: src/Apcu/bootstrap_zend.php [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    function apcu_inc($key, $step = 1, &$success = false)
+    {
+        return apc_inc($key, $step, $success);
+    }
+
+    function apcu_sma_info($limited = false)
+    {
+        return apc_sma_info($limited);
```
Comment (stof) [inline src/Apcu/bootstrap_zend.php]: We should avoid defining all these functions twice, as they are the same when using Zend Server or no

File: src/Apcu/bootstrap.php (hunk 9 above)
Comment (kategray) [inline src/Apcu/bootstrap.php]: `'phpdbg' !== PHP_SAPI` ?

**Comment by stof** [comment]
The APCUIterator polyfill should not be defined in case you skip the loading of other parts of the polyfill due to being in the CLI or phpdbg on Zend Server.

File: src/Apcu/bootstrap.php (hunk 9 above)
Comment (stof) [inline src/Apcu/bootstrap.php]: yes. Sorry, there was a typo in my comment. It should have said `strict`, not `struct`

File: src/Apcu/bootstrap_zend.php (hunk 11 above)
Comment (kategray) [inline src/Apcu/bootstrap_zend.php]: Will do.

**Comment by kategray** [comment]
Zend Server doesn't define the APCIterator class, so that code doesn't run.

File: src/Apcu/bootstrap.php [hunk 12]
```diff
@@ -13,18 +13,61 @@
     return;
 }
 
+if (extension_loaded('Zend Data Cache')) {
+    // Zend Data Cache refuses to load in the CLI, regardless of the configuration
+    if ('phpdbg' !== PHP_SAPI && 'cli' !== PHP_SAPI && false !== ini_get('zend_datacache.apc_compatibility')) {
+        require_once __DIR__.DIRECTORY_SEPARATOR.'bootstrap_zend.php';
```
Comment (nicolas-grekas) [inline src/Apcu/bootstrap.php]: instead of a separate bootstrap file, we should use the same strategy as other polyfills (see e.g. https://github.com/symfony/polyfill/blob/master/src/Iconv/bootstrap.php): a single bootstrap file that delegates "complex" implementations to static methods.

File: src/Apcu/bootstrap.php [hunk 13]
```diff
@@ -13,18 +13,61 @@
...
+    }
+}
+
 if (!function_exists('apcu_add')) {
-    function apcu_add($key, $var = null, $ttl = 0) { return apc_add($key, $var, $ttl); }
```
Comment (nicolas-grekas) [inline src/Apcu/bootstrap.php]: please keep these on a single line as they were, that'll help review, and as a change is unrelated to what you want to achieve here

File: tests/Apcu/ApcuTest.php (hunk 8 above)
Comment (nicolas-grekas) [inline tests/Apcu/ApcuTest.php]: the test suite already automatically does it, when using the static methods strategy + single line style in the bootstrap file

**Comment by nicolas-grekas** [comment]
@kategray any chance you might finish this PR? please advise, I can take over.

**Comment by kategray** [comment]
I'm swamped for a couple weeks.  I can do it after that, or you're welcome to.  Whichever you prefer.

**Comment by nicolas-grekas** [comment]
@kategray no pb, I took over :)
I removed the SAPI-related checks because I don't get them.
Should be green and ready.

**Comment by nicolas-grekas** [comment]
@kategray PS: http://sanfrancisco2017.live.symfony.com ;)

**Comment by fabpot** [comment]
Thank you @kategray.
