### PR TITLE
[PHP 8.0] add `get_resource_id` function

### LINKED ISSUE #259: Polyfill for get_resource_id()
As described in https://github.com/php/php-src/pull/5427

Anyone up to give it a try?

Be careful: we must also polyfill the behavior when a non-resource is passed (I don't know the behavior, it might be a warning or an exception - to be investigated).

### PR DESCRIPTION
**Pull request by IonBazan**
Resolves #259 

PHP 8.0 output for reference:
```
php > $res = fopen('test', 'w');
php > var_dump((int) $res, get_resource_id($res));
int(2)
int(2)
php > fclose($res);
php > var_dump((int) $res, get_resource_id($res));
int(2)
int(2)
php > $res = 10;
php > var_dump((int) $res, get_resource_id($res));
PHP Warning:  Uncaught TypeError: get_resource_id(): Argument #1 ($res) must be of type resource, int given in php shell code:1
Stack trace:
#0 php shell code(1): get_resource_id(10)
#1 {main}
  thrown in php shell code on line 1

Warning: Uncaught TypeError: get_resource_id(): Argument #1 ($res) must be of type resource, int given in php shell code:1
Stack trace:
#0 php shell code(1): get_resource_id(10)
#1 {main}
  thrown in php shell code on line 1
```

### CODE REVIEW

File: src/Php80/Php80.php [hunk 1]
```diff
@@ -57,6 +57,15 @@ public static function get_debug_type($value): string
         return (get_parent_class($class) ?: key(class_implements($class)) ?: 'class').'@anonymous';
     }
 
+    public static function get_resource_id($res): int
+    {
+        if (@\get_resource_type($res) === null) {
```
Comment (nicolas-grekas) [inline src/Php80/Php80.php:62]: let's optimize for the happy path:
`if (!\is_resource($res) && null === @get_resource_type($res)) {`

File: src/Php80/Php80.php [hunk 2]
```diff
@@ -57,6 +57,15 @@ public static function get_debug_type($value): string
...
+            throw new \TypeError(sprintf('Argument #1 ($res) must be of type resource, %s given', \gettype($res)));
```
Comment (nicolas-grekas) [inline src/Php80/Php80.php:63]: the message should match the one from PHP8
looking at https://wiki.php.net/rfc/consistent_type_errors, this should be more like
`Argument 1 passed to get_resource_id() must be of the type int, string given`

Comment (stof) [reply src/Php80/Php80.php:63]: well, `resource` rather than `int` of course :smile:

File: src/Php80/Php80.php (hunk 1 above)
Comment (stof) [reply src/Php80/Php80.php:62]: do we even need the `get_resource_type` check ?

Comment (nicolas-grekas) [reply src/Php80/Php80.php:62]: we need it for closed resources yes, that's an odd edge case.

**Comment by nicolas-grekas** [comment]
Thank you @IonBazan.
