### PR TITLE
mbstring polyfills must not raise value errors in PHP 7

### LINKED ISSUE #499: `ValueError` class not available in PHP < 8
The MBString polyfill supports PHP >= 7.2 but it makes use of the `ValueError` exception class, which was only introduced in PHP 8.

In a lot of instances, there is a version check before it is used, and in these cases there is no problem.

However, there are three unguarded locations that refer to the class, which will result in fatal errors on PHP 7:

https://github.com/symfony/polyfill/blob/731f6e101c33d3d1c2e4a8a87e4e4fe9b2f50f72/src/Mbstring/Mbstring.php#L837-L841

https://github.com/symfony/polyfill/blob/731f6e101c33d3d1c2e4a8a87e4e4fe9b2f50f72/src/Mbstring/Mbstring.php#L849-L851

https://github.com/symfony/polyfill/blob/731f6e101c33d3d1c2e4a8a87e4e4fe9b2f50f72/src/Mbstring/Mbstring.php#L1040-L1043

### PR DESCRIPTION
**Pull request by derrabus**
Fixes #499.

This PR changes all new mbstring polyfills on PHP 7 so that they trigger an oldschool PHP warning instead of raising a `ValueError`. The reason for that is that the `ValueError` class might not be available on PHP 7 and the behavior is more consitent with the other polyfills of the mbstring extension.

The somewhat weird side-effect is that we now polyfill a behavior that was never implemented in PHP.

### CODE REVIEW

File: tests/Php84/Php84Test.php [hunk 1]
```diff
@@ -229,7 +229,12 @@ public function testMbRTrim(string $expected, string $string, ?string $character
 
     public function testMbTrimException()
     {
-        $this->expectException(\ValueError::class);
+        if (PHP_VERSION_ID < 80000) {
+            $this->expectException(\ValueError::class);
+        } else {
+            $this->expectWarning();
+        }
```
Comment (jdreesen) [inline tests/Php84/Php84Test.php]: Shouldn't it be the other way around?
```suggestion
        if (PHP_VERSION_ID < 80000) {
            $this->expectWarning();
        } else {
            $this->expectException(\ValueError::class);
        }
```

Comment (derrabus) [reply tests/Php84/Php84Test.php]: Yes. I just caught this as well, but you were a bit faster. 🙂

File: src/Mbstring/bootstrap.php [hunk 2]
```diff
@@ -133,27 +133,27 @@ function mb_str_split($string, $length = 1, $encoding = null) { return p\Mbstrin
 }
 
 if (!function_exists('mb_str_pad')) {
-    function mb_str_pad(string $string, int $length, string $pad_string = ' ', int $pad_type = STR_PAD_RIGHT, ?string $encoding = null): string { return p\Mbstring::mb_str_pad($string, $length, $pad_string, $pad_type, $encoding); }
```
Comment (nicolas-grekas) [inline src/Mbstring/bootstrap.php:136]: what about a bootstrap80.php file to add the return types when running on PHP8+?

Comment (derrabus) [reply src/Mbstring/bootstrap.php:136]: That file already exists. ✌🏻

Comment (nicolas-grekas) [reply src/Mbstring/bootstrap.php:136]: ah indeed :) 
there are some failures to fix ;)

Comment (derrabus) [reply src/Mbstring/bootstrap.php:136]: Can you help we with those? Apparently, the test listener is skipping tests at a strange point in time which conflicts with the `expectWarning()` feature of PHPUnit. How do we solve that usually?

**Comment by nicolas-grekas** [comment]
Let's also address #506 here?

**Comment by nicolas-grekas** [comment]
Thank you @derrabus.

**Comment by eexit** [comment]
Hello,

I just updated my codebase with the latest changes, and my PHPStan breaks:

```php
\PHPStan\dumpType(mb_trim('foo'));
// Dumped type: mixed
```

```bash
$ composer info symfony/polyfill-php84
name     : symfony/polyfill-php84
descrip. : Symfony polyfill backporting some PHP 8.4+ features to lower PHP versions
keywords : compatibility, polyfill, portable, shim
versions : * v1.34.0
released : 2026-04-10, this week
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/polyfill-php84.git 88486db2c389b290bf87ff1de7ebc1e13e42bb06
dist     : [zip] https://api.github.com/repos/symfony/polyfill-php84/zipball/88486db2c389b290bf87ff1de7ebc1e13e42bb06 88486db2c389b290bf87ff1de7ebc1e13e42bb06
path     : /opt/php/vendor/symfony/polyfill-php84
names    : symfony/polyfill-php84

$ php -v
PHP 8.3.30 (cli) (built: Jan 30 2026 01:25:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.30, Copyright (c), by Zend Technologies
    with Xdebug v3.5.1, Copyright (c) 2002-2026, by Derick Rethans
```

Is there a way to fix this?

Thanks!

**Comment by nicolas-grekas** [comment]
Please open an issue. Commenting on a closed PR/issue is a good way to not get attention.
